import{i,S as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function o(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function e(r){if(r.ep)return;r.ep=!0;const t=o(r);fetch(r.href,t)}})();function d(a){return fetch(`https://pixabay.com/api/?key=42630881-770530465aa98d154d18ed059&q=${a}&image_type=photo&orientation=horizontal&safesearch=true`).then(e=>{if(!e.ok)throw new Error(`Error: ${e.status}`);return e.json()}).catch(e=>console.log(e))}const p=document.querySelector(".gallery");function f(a){if(a.hits.length===0)return i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});const s=a.hits.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href="${e.largeImageURL}">
                    <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
                </a>
            <div class="gallery-info">
                <p class="card">Likes <span class="card-value">${e.likes}</span></p>
                <p class="card">Views <span class="card-value">${e.views}</span></p>
                <p class="card">Comments <span class="card-value">${e.comments}</span></p>
                <p class="card">Downloads <span class="card-value">${e.downloads}</span></p>
            </div>
        </li>`).join("");return p.insertAdjacentHTML("afterbegin",s),new u(".gallery-link",{captionsData:"alt",captionDelay:250}).refresh(),s}const c=document.querySelector(".form"),m=document.querySelector(".form-input");document.querySelector(".gallery");const l=document.querySelector(".loader");c.addEventListener("submit",g);function g(a){a.preventDefault(),l.classList.remove("visually-hidden");const s=m.value.trim().toLowerCase().replaceAll(" ","+");if(s.length===0)return i.error({message:"Enter search image name",position:"topRight"});d(s).then(o=>f(o)),l.classList.add("visually-hidden"),c.reset()}
//# sourceMappingURL=commonHelpers.js.map
